version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./src/conoha/Dockerfile
    networks:
      - conoha-networks
    restart: always
    ports:
      - 8080:8080
  client:
    build:
      context: .
      dockerfile: ./src/discord/Dockerfile
    networks:
      - conoha-networks
    restart: always
    # volumes:
    #   - ./:/go/src
networks:
  conoha-networks:

