// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: conoha.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinecraftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MinecraftRequest) Reset() {
	*x = MinecraftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinecraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinecraftRequest) ProtoMessage() {}

func (x *MinecraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinecraftRequest.ProtoReflect.Descriptor instead.
func (*MinecraftRequest) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{0}
}

func (x *MinecraftRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MinecraftRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type MinecraftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Health  bool   `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *MinecraftResponse) Reset() {
	*x = MinecraftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinecraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinecraftResponse) ProtoMessage() {}

func (x *MinecraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinecraftResponse.ProtoReflect.Descriptor instead.
func (*MinecraftResponse) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{1}
}

func (x *MinecraftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MinecraftResponse) GetHealth() bool {
	if x != nil {
		return x.Health
	}
	return false
}

type SpellGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author    string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	SpellName string `protobuf:"bytes,2,opt,name=spell_name,json=spellName,proto3" json:"spell_name,omitempty"`
}

func (x *SpellGetRequest) Reset() {
	*x = SpellGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellGetRequest) ProtoMessage() {}

func (x *SpellGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellGetRequest.ProtoReflect.Descriptor instead.
func (*SpellGetRequest) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{2}
}

func (x *SpellGetRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SpellGetRequest) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

type SpellGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spell     string `protobuf:"bytes,1,opt,name=spell,proto3" json:"spell,omitempty"`
	ImagePath string `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SpellGetResponse) Reset() {
	*x = SpellGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellGetResponse) ProtoMessage() {}

func (x *SpellGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellGetResponse.ProtoReflect.Descriptor instead.
func (*SpellGetResponse) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{3}
}

func (x *SpellGetResponse) GetSpell() string {
	if x != nil {
		return x.Spell
	}
	return ""
}

func (x *SpellGetResponse) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SpellGetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SpellPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Author    string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	SpellName string   `protobuf:"bytes,4,opt,name=spell_name,json=spellName,proto3" json:"spell_name,omitempty"`
	ImagePath string   `protobuf:"bytes,5,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Seed      string   `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`
	Spells    []string `protobuf:"bytes,7,rep,name=spells,proto3" json:"spells,omitempty"`
}

func (x *SpellPostRequest) Reset() {
	*x = SpellPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellPostRequest) ProtoMessage() {}

func (x *SpellPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellPostRequest.ProtoReflect.Descriptor instead.
func (*SpellPostRequest) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{4}
}

func (x *SpellPostRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SpellPostRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SpellPostRequest) GetSpellName() string {
	if x != nil {
		return x.SpellName
	}
	return ""
}

func (x *SpellPostRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SpellPostRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *SpellPostRequest) GetSpells() []string {
	if x != nil {
		return x.Spells
	}
	return nil
}

type SpellPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spell     string `protobuf:"bytes,1,opt,name=spell,proto3" json:"spell,omitempty"`
	ImagePath string `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SpellPostResponse) Reset() {
	*x = SpellPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conoha_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellPostResponse) ProtoMessage() {}

func (x *SpellPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conoha_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellPostResponse.ProtoReflect.Descriptor instead.
func (*SpellPostResponse) Descriptor() ([]byte, []int) {
	return file_conoha_proto_rawDescGZIP(), []int{5}
}

func (x *SpellPostResponse) GetSpell() string {
	if x != nil {
		return x.Spell
	}
	return ""
}

func (x *SpellPostResponse) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *SpellPostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_conoha_proto protoreflect.FileDescriptor

var file_conoha_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40,
	0x0a, 0x10, 0x4d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x22, 0x45, 0x0a, 0x11, 0x4d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x6c, 0x6c,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x61, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x10, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x70, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x70, 0x65, 0x6c, 0x6c, 0x73, 0x22, 0x62, 0x0a, 0x11, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x65, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xaa, 0x01, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x6f, 0x68, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x4d,
	0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x12, 0x11, 0x2e, 0x4d, 0x69, 0x6e, 0x65, 0x63,
	0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x4d, 0x69,
	0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x2f, 0x0a, 0x08, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e,
	0x53, 0x70, 0x65, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x11, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conoha_proto_rawDescOnce sync.Once
	file_conoha_proto_rawDescData = file_conoha_proto_rawDesc
)

func file_conoha_proto_rawDescGZIP() []byte {
	file_conoha_proto_rawDescOnce.Do(func() {
		file_conoha_proto_rawDescData = protoimpl.X.CompressGZIP(file_conoha_proto_rawDescData)
	})
	return file_conoha_proto_rawDescData
}

var file_conoha_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_conoha_proto_goTypes = []interface{}{
	(*MinecraftRequest)(nil),  // 0: MinecraftRequest
	(*MinecraftResponse)(nil), // 1: MinecraftResponse
	(*SpellGetRequest)(nil),   // 2: SpellGetRequest
	(*SpellGetResponse)(nil),  // 3: SpellGetResponse
	(*SpellPostRequest)(nil),  // 4: SpellPostRequest
	(*SpellPostResponse)(nil), // 5: SpellPostResponse
}
var file_conoha_proto_depIdxs = []int32{
	0, // 0: ConohaService.Minecraft:input_type -> MinecraftRequest
	2, // 1: ConohaService.SpellGet:input_type -> SpellGetRequest
	4, // 2: ConohaService.SpellPost:input_type -> SpellPostRequest
	1, // 3: ConohaService.Minecraft:output_type -> MinecraftResponse
	3, // 4: ConohaService.SpellGet:output_type -> SpellGetResponse
	5, // 5: ConohaService.SpellPost:output_type -> SpellPostResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conoha_proto_init() }
func file_conoha_proto_init() {
	if File_conoha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conoha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinecraftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conoha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinecraftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conoha_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conoha_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conoha_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conoha_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conoha_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conoha_proto_goTypes,
		DependencyIndexes: file_conoha_proto_depIdxs,
		MessageInfos:      file_conoha_proto_msgTypes,
	}.Build()
	File_conoha_proto = out.File
	file_conoha_proto_rawDesc = nil
	file_conoha_proto_goTypes = nil
	file_conoha_proto_depIdxs = nil
}
