// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: conoha.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConohaServiceClient is the client API for ConohaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConohaServiceClient interface {
	Minecraft(ctx context.Context, in *MinecraftRequest, opts ...grpc.CallOption) (*MinecraftResponse, error)
}

type conohaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConohaServiceClient(cc grpc.ClientConnInterface) ConohaServiceClient {
	return &conohaServiceClient{cc}
}

func (c *conohaServiceClient) Minecraft(ctx context.Context, in *MinecraftRequest, opts ...grpc.CallOption) (*MinecraftResponse, error) {
	out := new(MinecraftResponse)
	err := c.cc.Invoke(ctx, "/ConohaService/Minecraft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConohaServiceServer is the server API for ConohaService service.
// All implementations must embed UnimplementedConohaServiceServer
// for forward compatibility
type ConohaServiceServer interface {
	Minecraft(context.Context, *MinecraftRequest) (*MinecraftResponse, error)
	mustEmbedUnimplementedConohaServiceServer()
}

// UnimplementedConohaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConohaServiceServer struct {
}

func (UnimplementedConohaServiceServer) Minecraft(context.Context, *MinecraftRequest) (*MinecraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Minecraft not implemented")
}
func (UnimplementedConohaServiceServer) mustEmbedUnimplementedConohaServiceServer() {}

// UnsafeConohaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConohaServiceServer will
// result in compilation errors.
type UnsafeConohaServiceServer interface {
	mustEmbedUnimplementedConohaServiceServer()
}

func RegisterConohaServiceServer(s grpc.ServiceRegistrar, srv ConohaServiceServer) {
	s.RegisterService(&ConohaService_ServiceDesc, srv)
}

func _ConohaService_Minecraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinecraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConohaServiceServer).Minecraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ConohaService/Minecraft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConohaServiceServer).Minecraft(ctx, req.(*MinecraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConohaService_ServiceDesc is the grpc.ServiceDesc for ConohaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConohaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ConohaService",
	HandlerType: (*ConohaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Minecraft",
			Handler:    _ConohaService_Minecraft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conoha.proto",
}
